name: Branching convention check
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint branch name
        uses: lekterable/branchlint-action@2.1.0
        with:
          allowed: (feat|fix|chore|docs)/\d{1,5}-[a-zA-Z0-9-]+$
